# This file is generated by cargo2rulesmk.py --run --config cargo2rulesmk.json.
# Do not modify this file as changes will be overridden on upgrade.

LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)
MODULE_CRATE_NAME := protobuf
MODULE_SRCS := \
	$(LOCAL_DIR)/src/lib.rs \

OUT_FILE := $(call TOBUILDDIR,$(MODULE))/version.rs
$(OUT_FILE): $(MODULE)/out/version.rs
	@echo copying $< to $@
	@$(MKDIR)
	cp $< $@

MODULE_RUST_ENV += OUT_DIR=$(dir $(OUT_FILE))

MODULE_SRCDEPS := $(OUT_FILE)
MODULE_RUST_EDITION := 2021
MODULE_RUSTFLAGS += \
	--cfg 'feature="default"' \

MODULE_LIBRARY_DEPS := \
	external/rust/crates/once_cell \
	external/rust/crates/protobuf-support \
	external/rust/crates/thiserror \

include make/library.mk
